config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticate :user do
    resources :boards, except: [ :new ] do
      resources :memberships, controller: "board_memberships", only: [ :index, :create, :destroy ]
      resources :lists, only: [ :create, :update, :destroy ] do
        patch :update_position, on: :member
        resources :cards, only: [ :create, :edit, :update, :destroy ] do
          patch :update_position, on: :member
          resources :comments do
            get :cancel, on: :member
          end
        end
      end
    end
  end

  root "page#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
  belongs_to :user, optional: true
  validates :content, presence: true, length: { maximum: 150 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_card

  def create
    @comment = @card.comments.build(comment_params)
    @comment.user = current_user if defined?(current_user)

    if @comment.save
      respond_to do |format|
        format.turbo_stream { render :create, locals: { board: @board, list: @list, card: @card, comment: @comment } }
        format.json { render :show, status: :created, location: @comment }
      end
    else
      respond_to do |format|
        format.turbo_stream { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @comment = @card.comments.find(params[:id])

    unless turbo_frame_request?
      redirect_to edit_board_list_card_path(@board, @list, @card), alert: "Please use the Turbo form to edit the comment."
    end
  end

  def update
    @comment = @card.comments.find(params[:id])

    if @comment.update(comment_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.turbo_stream { render :update, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    @comment = @card.comments.find(params[:id])

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @comment = @card.comments.find(params[:id])
    @comment.destroy

    if @comment.user == current_user
      respond_to do |format|
        format.html { redirect_to board_list_card_path(@board, @list, @card), notice: "Komentarz usunięty." }
        format.turbo_stream { render :destroy, locals: { board: @board, list: @list, card: @card, comment: @comment } }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_card
    @board = Board.find(params[:board_id])
    @list = @board.lists.find(params[:list_id])
    @card = @list.cards.find(params[:card_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <li class="w-full flex flex-col gap-1">
    <div class="flex items-center gap-3">
      <h5 class="font-semibold"><%= comment.user.nil? ? "Anonymous" : comment.user.email %></h5>
      <span class="text-xs text-neutral-400"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></span>
    </div>
    <div class="p-4 border border-neutral-600 rounded bg-neutral-900" id="comment-content-<%= comment.id %>">
      <%= comment.content %>
    </div>
    <% if comment.user == current_user %>
      <div class="flex items-center border-g divide-x divide-neutral-600">
        <%= link_to "Edytuj", edit_board_list_card_comment_path(@board, @list, @card, comment),
        class: "text-left hover:cursor-pointer text-xs px-2" %>
        <%= button_to "Usuń", board_list_card_comment_path(@board, @list, @card, comment), method: :delete, data: {turbo_confirm: "Czy na pewno chcesz usunąć komentarz?"},
        class: "text-red-400 text-left hover:cursor-pointer text-xs px-2" %>
      </div>
    <% end %>
  </li>
<% end %>

app/views/comments/_form.html.erb
 <%= turbo_frame_tag id="new_comment" do %>
  <%= form_with model: [board, list, card, comment], class: "flex flex-col gap-4 w-full" do |form| %>
    <div>
      <%= form.text_area :content, placeholder: "Napisz komentarz...", autofocus: comment.persisted?, class: "input w-full" %>
    </div>
    <div>
      <%= form.submit comment.persisted? ? "Zapisz" : "Dodaj", class: comment.persisted? ? "btn btn-primary" : "btn" %>
      <% if comment.persisted? %>
        <%= link_to "Odrzuć zmiany", cancel_board_list_card_comment_path(@board, @list, @card, comment), data: { turbo_stream: true }, class: "btn"%>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/comments/cancel.turbo_stream.erb
<%= turbo_stream.replace dom_id(@comment) do %>
  <%= render partial: "comment", locals: { comment: @comment } %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments" do %>
  <%= render partial: "comment", locals: {comment: @comment} %>
<% end %>
<%= turbo_stream.replace "new_comment",
    partial: "form",
    locals: {board: @board, list: @list, card: @card, comment: Comment.new}
%>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag dom_id(@comment) do %>
  <%= render "form", board: @board, list: @list, card: @card, comment: @comment %>
<% end %>

app/views/comments/new.turbo_stream.erb
<%= turbo_stream.replace "new_comment" do %>
  <%= render partial: "comments/form", locals: { board: @board, list: @list, card: @card, comment: @comment } %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@comment) do %>
  <%= render partial: "comment", locals: { comment: @comment } %>
<% end %>