config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticate :user do
    resources :boards, except: [ :new ] do
      resources :memberships, controller: "board_memberships", only: [ :index, :create, :destroy ]
      resources :lists, only: [ :create, :update, :destroy ] do
        patch :update_position, on: :member
        resources :cards, only: [ :create, :edit, :update, :destroy ] do
          patch :update_position, on: :member
          resources :comments do
            get :cancel, on: :member
          end
        end
      end
    end
  end

  root "page#index"
end

app/views/shared/_navbar.html.erb
<div class="fixed flex items-center justify-between w-full top-0 py-3 px-4 bg-neutral-800 text-white border-b border-b-neutral-500 shadow-md z-50">
  <%= link_to "Kanbanly", user_signed_in? ? boards_path : root_path, class: "text-3xl font-bold cursor-pointer" %>
  <% if user_signed_in? %>
    <div class="absolute top-4 right-4 translate dropdown dropdown-end">
      <div tabindex="0" role="button">
        <div class="cursor-pointer ring-primary bg-neutral-950 ring-offset-base-100 w-8 h-8 rounded-full ring ring-offset-2 flex items-center justify-center relative">
          <span class="absolute top-1/2 right-1/2 translate-x-1/2 -translate-y-1/2 uppercase font-semibold"><%= current_user.email.slice(0,1) %></span>
        </div>
      </div>
      <ul class="dropdown-content menu rounded-box bg-base-100 shadow-sm border border-neutral-600">
        <li class="min-w-[150px]"><%= button_to "Wyloguj się", destroy_user_session_path, method: :delete, class:"min-w-[150px] text-left hover:cursor-pointer" %></li>
      </ul>
    </div>
  <% else %>
    <%= link_to "Zaloguj się", new_user_session_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_notifications.html.erb
<% if message %>
  <div 
  class="toast transition transform duration-100"   
  data-controller="notifications"
  data-notification-delay-value="2000"
  class="transition transform duration-1000 hidden"
  data-transition-enter-from="opacity-0 translate-x-6"
  data-transition-enter-to="opacity-100 translate-x-0"
  data-transition-leave-from="opacity-100 translate-x-0"
  data-transition-leave-to="opacity-0 translate-x-6">
    <div class="alert alert-info">
      <span class="text-white"><%= message %></span>
      <button class="cursor-pointer text-white hover:text-neutral-300 transition-all" data-action="notifications#hide"><%= lucide_icon("x", class: "w-4") %></button>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="bg-neutral-800 text-white py-8 px-4 w-[250px] border-r border-r-neutral-500 shadow-md flex flex-col gap-4">
  <div class="flex flex-col gap-3">
    <% if current_user.accessible_boards.any? %>
      <div class="flex justify-between items-center">
        <span class="font-semibold text-neutral-300 text-sm">Dostępne tablice</span><span class="text-sm text-neutral-500 flex gap-0.5">
          <div><%= current_user.accessible_boards.count %></div>
          <div>/</div>
          <div><%= BOARDS_LIMIT %></div>
        </span>
        <%= render "boards/new_board_modal", modal_id: "modal_5", icon: "plus", trigger_style_classes: "text-lg text-netural-300 px-1.5 hover:bg-neutral-500 rounded-md transition-all" %>
      </div>
      <% current_user.accessible_boards.each do |board| %>
        <div class="relative group">
          <%= link_to board, class: "flex gap-1 items-center py-2 px-2 bg-neutral-700 rounded-md text-neutral-200 hover:bg-neutral-500 shadow-md transition-all overflow-hidden" do %>
            <span>📋</span><span><%= board.title %></span>
          <% end %>
          <div class="absolute top-1 right-1 transale dropdown dropdown-start">
            <button class="group-hover:flex hidden active:flex focus:flex items-center justify-center ml-auto rounded-full p-1 bg-neutral-600 hover:bg-neutral-500 transition-all">
              <%= lucide_icon("ellipsis-vertical", class: "w-4") %>
            </button>
            <ul class="dropdown-content menu w-52 rounded-box bg-base-100 shadow-sm min-w-[150px] border border-neutral-600">
              <li class="min-w-[150px]"><%= link_to "Edytuj", edit_board_path(board), class:"min-w-[150px] text-left hover:cursor-pointer" %></li>
              <li class="min-w-[150px]"><%= link_to "Członkowie", board_memberships_path(board), class:"min-w-[150px] text-left hover:cursor-pointer" %></li>
              <% if board.user == current_user || board.admin?(current_user) %>
                <li class="min-w-[150px]"><%= button_to "Usuń tablice", board, method: :delete, data: { turbo_confirm: "Czy na pewno chcesz usunąć tablicę?" }, class:"text-red-400 min-w-[150px] text-left hover:cursor-pointer" %></li>
              <% elsif board_membership = BoardMembership.find_by(user: current_user, board: board) %>
                <li class="min-w-[150px]">
                  <%= button_to "Opuść tablice", 
                  board_membership_path(board, board_membership), 
                      method: :delete, 
                      data: { turbo_confirm: "Czy na pewno chcesz usunąć dostęp do tablicy?" },
                  class:"text-red-400 min-w-[150px] text-left hover:cursor-pointer" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% else%>
      <span class="font-semibold text-neutral-300 text-sm">Dostępne tablice</span>
      <div class="flex flex-col items-center justify-center gap-4 bg-neutral-900 p-4 rounded">
        <span class="text-sm text-neutral-300">Brak tablic</span>
        <%= image_tag "no-boards.svg", alt: "boards empty state", class: "w-18 opacity-80"  %>
        <%= render "boards/new_board_modal", modal_id: "modal_5", trigger_text: "Dodaj tablicę", trigger_style_classes: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>