config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticate :user do
    resources :boards, except: [ :new ] do
      resources :memberships, controller: "board_memberships", only: [ :index, :create, :destroy ]
      resources :lists, only: [ :create, :update, :destroy ] do
        patch :update_position, on: :member
        resources :cards, only: [ :create, :edit, :update, :destroy ] do
          patch :update_position, on: :member
          resources :comments do
            get :cancel, on: :member
          end
        end
      end
    end
  end

  root "page#index"
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  validates :title, presence: true, length: { maximum: 30 }

  has_many :board_memberships, dependent: :destroy
  has_many :members, through: :board_memberships, source: :user

  validate :board_limit


  def admins
    board_memberships.where(role: "admin").map(&:user)
  end

  def admin?(user)
    board_memberships.exists?(user: user, role: "admin")
  end

  private

  def board_limit
    if user.boards.count >= BOARDS_LIMIT
      errors.add(:base, "Osiągnąłeś limit tablic")
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [ :show, :edit, :update, :destroy ]
  before_action :authorize_board_access!, only: [ :show ]
  before_action :authorize_board_owner!, only: [ :edit, :update, :destroy ]

  # GET /boards or /boards.json
  def index
    @boards = current_user.accessible_boards
  end

  # GET /boards/1 or /boards/1.json
  def show
    @board = Board.find(params[:id])
    @lists = @board.lists.order(:position)

    @list_count = @board.lists.count
  end


  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: "Tablica została utworzona." }
        format.json { render :show, status: :created, location: @board }
      else
        format.turbo_stream { render partial: "boards/form", formats: [ :html ], locals: { board: @board }, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: "Tablica została zaktualizowana." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_path, status: :see_other, notice: "Tablica została usunięta." }
      format.json { head :no_content }
    end
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title)
    end

    def authorize_board_access!
      unless @board.user == current_user || @board.members.include?(current_user)
        redirect_to boards_path
      end
    end

    def authorize_board_owner!
      unless @board.user == current_user
        redirect_to boards_path
      end
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board_card.html.erb
<div id="<%= dom_id board %>" class="relative">
  <%= link_to board, class: "block" do %>
    <div class="flex flex-col items-center justify-center gap-4 border bg-neutral-900 border-neutral-500 shadow-md rounded-md p-8 h-[200px]">
      <p class="se">
        <%= board.title %>
      </p>
    </div>
  <% end %>
  <span class="text-neutral-500 absolute top-4 left-4">
    <div class="inline-grid *:[grid-area:1/1]">
      <div class="status status-success animate-ping"></div>
      <div class="status status-success"></div>
    </div>
    Tablica
  </span>
  <div class="absolute top-4 right-4 translate dropdown dropdown-start">
    <button class="flex items-center justify-center ml-auto rounded-full p-1 bg-neutral-600 hover:bg-neutral-500 transition-all">
      <%= lucide_icon("ellipsis", class: "w-4") %>
    </button>
    <ul class="dropdown-content menu w-52 rounded-box bg-base-100 shadow-sm min-w-[150px] border border-neutral-600">
      <li class="min-w-[150px]"><%= link_to "Edytuj", edit_board_path(board), class:"min-w-[150px] text-left hover:cursor-pointer" %></li>
      <li class="min-w-[150px]"><%= link_to "Członkowie", board_memberships_path(board), class:"min-w-[150px] text-left hover:cursor-pointer" %></li>
      <% if board.user == current_user || board.admin?(current_user) %>
        <li class="min-w-[150px]"><%= button_to "Usuń tablice", board, method: :delete, class:"text-red-400 min-w-[150px] text-left hover:cursor-pointer" %></li>
      <% elsif board_membership = BoardMembership.find_by(user: current_user, board: board) %>
        <li class="min-w-[150px]">
          <%= button_to "Opuść tablice", 
                  board_membership_path(board, board_membership), 
                      method: :delete, 
                      data: { turbo_confirm: "Czy na pewno chcesz usunąć dostęp do tablicy?" },
                  class:"text-red-400 min-w-[150px] text-left hover:cursor-pointer" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/boards/_create_board_card.html.erb
<div class="flex flex-col items-center justify-center gap-4 bg-neutral-600 p-4 rounded h-[200px]">
  <%= render "boards/new_board_modal", modal_id: "modal_5", trigger_text: "Dodaj tablicę", trigger_style_classes: "btn btn-primary" %>
</div>

app/views/boards/_empty_state.html.erb
<div class="w-full flex items-center justify-center">
  <div class="flex flex-col items-center justify-center gap-4 bg-neutral-900 p-12 rounded w-full max-w-[650px]">
    <span class="text-sm text-neutral-300">Brak tablic</span>
    <%= image_tag "no-boards.svg", alt: "boards empty state", class: "w-18 opacity-80" %>
    <div>
      <%= render "boards/new_board_modal", modal_id: "modal_5", trigger_text: "Dodaj tablicę", trigger_style_classes: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board, class: "contents") do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
      <ul class="list-disc ml-6">
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col gap-4">
    <div class="flex flex-col gap-2">
      <%= form.label "Nazwa" %>
      <%= form.text_field :title, class: ["input", {"border-gray-400 focus:outline-blue-600": board.errors[:title].none?, "border-red-400 focus:outline-red-600": board.errors[:title].any?}] %>
    </div>
    <div>
      <%= form.hidden_field :user_id,value: current_user.id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": board.errors[:user_id].none?, "border-red-400 focus:outline-red-600": board.errors[:user_id].any?}] %>
    </div>
    <div class="inline">
      <%= form.submit board.persisted? ? "Zapisz" : "Utwórz tablicę", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/boards/_new_board_modal.html.erb
<%# Ensure modal_id is unique %>
<% raise "modal_id is required" if modal_id.blank? %>
<% icon ||= "" %>
<% trigger_text ||= "" %>
<% trigger_style_classes ||= "btn" %>
<button class="<%= trigger_style_classes %> cursor-pointer" onclick="document.getElementById('<%= modal_id %>').showModal()">
  <% if icon.present? %>
    <%= lucide_icon(icon, class: "w-4") %>
  <% end %>
  <%= trigger_text %>
</button>
<dialog id="<%= modal_id %>" class="modal modal-bottom sm:modal-middle">
  <div class="modal-box">
    <div class="md:w-2/3 w-full flex flex-col gap-4">
      <h1 class="font-bold text-4xl">Nowa tablica</h1>
      <%= render "boards/form", board: Board.new %>
    </div>
    <div class="modal-action absolute -top-3 right-3">
      <form method="dialog">
        <button class="p-2 hover:cursor-pointer">
          <%= lucide_icon("x", class: "w-4") %>
        </button>
      </form>
    </div>
  </div>
</dialog>

app/views/boards/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Boards#create</h1>
  <p>Find me in app/views/boards/create.html.erb</p>
</div>

app/views/boards/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Boards#destroy</h1>
  <p>Find me in app/views/boards/destroy.html.erb</p>
</div>

app/views/boards/edit.html.erb
<div class="md:w-2/3 w-full flex flex-col gap-8">
  <h1 class="font-bold text-4xl">Edytuj tablice</h1>
  <%= render "form", board: @board %>
</div>

app/views/boards/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tablice</h1>
  </div>
  <% if @boards.any? %>
    <div id="boards" class="min-w-full grid grid-cols-3 gap-6 mt-6">
      <% @boards.each do |board| %>
        <%= render "boards/board_card", board: board %>
      <% end %>
      <%= render "boards/create_board_card" %>
    </div>
  <% else %>
    <div class="mt-6">
      <%= render "boards/empty_state" %>
    </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<div class="flex justify-between mb-6 fixed boards-header-width z-40 py-6 -mt-6 backdrop-blur-sm">
  <h1 class="text-2xl font-bold text-neutral-300"><%= @board.title %></h1>
  <div id="list-counter" class="text-neutral-400 text-sm p-2 bg-neutral-800 rounded shadow">
    Listy: <%= @list_count %> / <%= BOARD_LIST_LIMIT %>
  </div>
</div>
<div class="flex gap-4 mt-16">
  <div 
    data-sortable-url-value="<%= update_position_board_list_path(@board, ':id') %>" 
    data-controller="sortable" 
    class="flex gap-4 items-start"
  >
    <%= render 'lists/lists', board: @board %>
  </div>
  <%= render 'lists/new_list_form', board: @board %>
</div>

app/views/boards/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Boards#update</h1>
  <p>Find me in app/views/boards/update.html.erb</p>
</div>