config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticate :user do
    resources :boards, except: [ :new ] do
      resources :memberships, controller: "board_memberships", only: [ :index, :create, :destroy ]
      resources :lists, only: [ :create, :update, :destroy ] do
        patch :update_position, on: :member
        resources :cards, only: [ :create, :edit, :update, :destroy ] do
          patch :update_position, on: :member
          resources :comments do
            get :cancel, on: :member
          end
        end
      end
    end
  end

  root "page#index"
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  validates :title, presence: true, length: { maximum: 30 }
  has_rich_text :description
  has_many :comments, dependent: :destroy
  acts_as_list scope: :list_id

  validate :cards_in_list_limit

  private


  def cards_in_list_limit
    if list.cards.count >= CARDS_IN_LIST
      errors.add(:base, "Osiągnąłeś limit kart")
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board
  before_action :set_list
  before_action :set_card, only: [ :edit, :update, :destroy, :update_position ]
  before_action :authorize_board_access!

  def create
    @card = @list.cards.build(card_params)

    if @card.save
      redirect_to board_path(@board), notice: "Karta została dodana!"
    else
      redirect_to board_path(@board), status: :unprocessable_entity
    end
  end

  def edit
    unless turbo_frame_request?
      redirect_to board_path(@board)
    end
  end

  def update
    if @card.update(card_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @card.destroy
      redirect_to board_path(@board), status: :see_other, notice: "Karta została usunięta!"
    else
      redirect_to board_path(@board), alert: "Nie udało się usunąć karty."
    end
  end

  def update_position
    @card.update(list_id: params[:new_list_id], position: params[:position].to_i + 1)
    head :ok
  end

  private

  def set_board
    @board = Board.find(params[:board_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to boards_path, alert: "Nie znalezieno tablicy."
  end

  def set_list
    @list = @board.lists.find(params[:list_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to board_path(@board), alert: "Nie znaleziono listy."
  end

  def set_card
    @card = @list.cards.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to board_list_path(@board, @list), alert: "Nie znalezino karty."
  end

  def card_params
    params.require(:card).permit(:title, :description)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_actions.html.erb
<div class="absolute top-1 right-3 dropdown dropdown-start">
  <button class="group-hover:flex hidden active:flex focus:flex items-center justify-center ml-auto rounded-full p-1 bg-neutral-600 hover:bg-neutral-500 transition-all">
    <%= lucide_icon("ellipsis-vertical", class: "w-4") %>
  </button>
  <ul class="dropdown-content menu w-52 rounded-box bg-base-100 shadow-sm min-w-[150px] border border-neutral-600">
    <li class="min-w-[150px]">
      <%= button_to "Usuń kartę", board_list_card_path(board, list, card), method: :delete,  data: { turbo_confirm: "Czy na pewno chcesz usunąć kartę?" },
          class: "text-red-400 min-w-[150px] text-left hover:cursor-pointer" %>
    </li>
  </ul>
</div>

app/views/cards/_card.html.erb
<div class="relative group" data-card-sortable-id="<%= card.id %>">
  <%= link_to edit_board_list_card_path(board, list, card), data: { turbo_frame: "modal", controller: "modal", action: "click->modal#open" } do %>
    <div class="bg-neutral-700 hover:bg-neutral-500 p-2 rounded shadow flex flex-col transition-all overflow-hidden">
      <p class="font-semibold text-neutral-200"><%= card.title %></p>
      <% if card.description&.body.present? %>
        <div class="line-clamp-5 text-neutral-200 mt-3"><%= card.description %></div>
      <% end %>
    </div>
  <% end %>
  <%= render 'cards/actions', board: board, list: list, card: card %>
</div>

app/views/cards/_cards.html.erb
<div class="flex flex-col gap-2"  id="list_<%= list.id %>_cards" data-controller="card-sortable"  data-card-sortable-url-value="<%= update_position_board_list_card_path(@board, list, ':id') %>"  >
  <% list.cards.order(:position).each do |card| %>
    <%= render 'cards/card', board: board, list: list, card: card %>
  <% end %>
</div>

app/views/cards/_form.html.erb
<div class="relative rounded w-[850px] min-h-[400px] border border-neutral-500 flex flex-col items-center shadow-md bg-neutral-800 p-4">
  <div class=" flex justify-between w-full mb-4">
    <div class="transale dropdown dropdown-start">
      <button class="flex items-center justify-center ml-auto rounded-full w-[40px] bg-neutral-800 hover:bg-neutral-500 transition-all">
        <%= lucide_icon("ellipsis", class: "w-4") %>
      </button>
      <ul class="dropdown-content menu rounded-box bg-base-100 shadow-sm border border-neutral-600">
        <li class="min-w-[150px]">
          <%= button_to "Usuń kartę", board_list_card_path(board, list, card), method: :delete, data: { turbo_confirm: "Czy na pewno chcesz usunąć kartę?" }, class: "text-red-400 min-w-[150px] hover:cursor-pointer text-left" %>
        </li>
      </ul>
    </div>
    <button class="cursor-pointer hover:text-white transition-all" data-action="click->modal#close"><%= lucide_icon("x", class: "w-12") %></button>
  </div>
  <%= form_with(model: [board, list, card], class: "contents",  data: {action: "turbo:submit-end->modal#closeIfSuccessful"}) do |form| %>
    <% if card.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
        <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>
        <ul class="list-disc ml-6">
          <% card.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="flex flex-col gap-8 w-full">
      <div class="flex flex-col w-full gap-2">
        <%= form.label "Tytuł" %>
        <%= form.text_field :title, class: ["input w-full", {"border-gray-400 focus:outline-blue-600": card.errors[:title].none?, "border-red-400 focus:outline-red-600": card.errors[:title].any?}] %>
      </div>
      <div class="flex flex-col w-full gap-2">
        <%= form.label "Opis" %>
        <%= form.rich_text_area :description, class: "text-neutral-200", rows: "15" %>
      </div>
      <div class="inline w-full">
        <%= form.submit "Zapisz", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
  <div class="w-full mt-12">
    <%= render "comments/form", board: board, list: list, card: card, comment: Comment.new  %>
    <ul class="flex flex-col gap-3 mt-4" id="comments">
      <% @card.comments.order(created_at: :desc).each do |comment| %>
        <%= render "comments/comment", comment: comment %>
      <% end %>
    </ul>
  </div>
</div>

app/views/cards/edit.html.erb
<turbo-frame id="modal">
  <div class="modal-overlay py-12 fixed backdrop-blur-sm w-full h-full z-99999999 flex justify-center items-start overflow-y-scroll" data-controller="modal">
    <div class="modal-content">
      <%= render "form", board: @board, list: @list, card: @card %>
    </div>
  </div>
</turbo-frame>

app/views/cards/update.turbo_stream.erb
<%= turbo_stream.replace "list_#{@list.id}_cards", partial: "cards", locals: {board: @board, list: @list, card: @card} %>